#!/bin/bash -p
#Desc: UDPGW Enabler[autostart]

#AUTOMATIC START
echo "Desc: UDPGW Enabler[auto-starter]"
echo "============="
echo "UDPGW -ON"

screen -dmS udpgw /bin/udpgw --listen-addr 127.0.0.1:7200 --max-clients 1000 --max-connections-for-client 100